from djongo import models as mongo_models
from datetime import datetime
import pytz

def default_time():
    return pytz.utc.localize(datetime.now())

# Model for POPMSA006 Data
class POPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField()
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID
    

# Temporary Model for POPMSA006 Data
class TemporaryPOPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField()
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID
    


# Temporary Model for POPMSA006 Data
class TodayPOPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField()
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID
    

# Last 7 days Model for POPMSA006 Data
class Last7DaysPOPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField(default=default_time)
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID
    

# Last 30 days Model for POPMSA006 Data
class Last30DaysPOPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField(default=default_time)
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID
    

# Last 1 year Model for POPMSA006 Data
class ThisYearPOPMSA006(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_time = mongo_models.DateTimeField(default=default_time)
    dev_ID = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ac_temp_1 = mongo_models.FloatField()
    ac_temp_2 = mongo_models.FloatField()
    env_temp_1 = mongo_models.FloatField()
    env_hum_1 = mongo_models.FloatField()
    env_dp_1 = mongo_models.FloatField()
    env_temp_2 = mongo_models.FloatField()
    env_hum_2 = mongo_models.FloatField()
    env_dp_2 = mongo_models.FloatField()
    door_state_1 = mongo_models.FloatField()
    door_state_2 = mongo_models.FloatField()
    smoke_state = mongo_models.FloatField()
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    avln = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    avll = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    avc = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    totkw = mongo_models.FloatField()
    totkva = mongo_models.FloatField()
    totkvar = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    avpf = mongo_models.FloatField()
    f = mongo_models.FloatField()
    totnkwh = mongo_models.FloatField()
    totnkvah = mongo_models.FloatField()
    totnkvarh = mongo_models.FloatField()
    timestamp = mongo_models.FloatField()

    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.dev_ID