# Generated by Django 4.1 on 2024-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdevicestate',
            name='date',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('TODAY', 'Today'), ('LAST_7_DAYS', 'This Week'), ('LAST_30_DAYS', 'This Month'), ('THIS_YEAR', 'This Year')], db_column='date', max_length=256),
        ),
    ]
