# Generated by Django 4.1 on 2024-06-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_alter_popdevicestate_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnyNowDataModelCPM',
        ),
        migrations.DeleteModel(
            name='RTModelCPM',
        ),
        migrations.DeleteModel(
            name='Temporary6HourRTModelCPM',
        ),
        migrations.DeleteModel(
            name='TemporaryHourlyRTModelCPM',
        ),
        migrations.DeleteModel(
            name='TemporaryRTModelCPM',
        ),
        migrations.DeleteModel(
            name='ThisMonthRTModelCPM',
        ),
        migrations.DeleteModel(
            name='ThisWeekRTModelCPM',
        ),
        migrations.DeleteModel(
            name='ThisYearRTModelCPM',
        ),
        migrations.DeleteModel(
            name='TodayRTModelCPM',
        ),
    ]
