# Generated by Django 4.1 on 2024-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0004_last30dayspopmsa006_last7dayspopmsa006_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popdevicestate',
            name='date',
            field=models.CharField(choices=[('TODAY', 'Today'), ('LAST_7_DAYS', 'Last 7 days'), ('LAST_30_DAYS', 'Last 30 days'), ('THIS_YEAR', 'This Year')], db_column='date', max_length=256),
        ),
    ]
