# Generated by Django 4.1 on 2024-06-09 06:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0005_alter_popdevicestate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last30DaysPOPMSA006ExternalInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deviceCode', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('mainVoltage', models.FloatField()),
                ('rectifierCurrent', models.FloatField()),
                ('loadCurrentValue', models.FloatField()),
                ('loadVoltageValue', models.FloatField()),
                ('batteryVoltageValue', models.FloatField()),
                ('batteryCurrentValue', models.FloatField()),
                ('batteryTemperatureValue', models.FloatField()),
                ('batteryTimeLeftValue', models.FloatField()),
                ('batteryRemainingCapacityValue', models.FloatField()),
                ('batteryUsedCapacityValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Last7DaysPOPMSA006ExternalInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deviceCode', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('mainVoltage', models.FloatField()),
                ('rectifierCurrent', models.FloatField()),
                ('loadCurrentValue', models.FloatField()),
                ('loadVoltageValue', models.FloatField()),
                ('batteryVoltageValue', models.FloatField()),
                ('batteryCurrentValue', models.FloatField()),
                ('batteryTemperatureValue', models.FloatField()),
                ('batteryTimeLeftValue', models.FloatField()),
                ('batteryRemainingCapacityValue', models.FloatField()),
                ('batteryUsedCapacityValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='POPMSA006ExternalInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deviceCode', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('mainVoltage', models.FloatField()),
                ('rectifierCurrent', models.FloatField()),
                ('loadCurrentValue', models.FloatField()),
                ('loadVoltageValue', models.FloatField()),
                ('batteryVoltageValue', models.FloatField()),
                ('batteryCurrentValue', models.FloatField()),
                ('batteryTemperatureValue', models.FloatField()),
                ('batteryTimeLeftValue', models.FloatField()),
                ('batteryRemainingCapacityValue', models.FloatField()),
                ('batteryUsedCapacityValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ThisYearPOPMSA006ExternalInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deviceCode', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('mainVoltage', models.FloatField()),
                ('rectifierCurrent', models.FloatField()),
                ('loadCurrentValue', models.FloatField()),
                ('loadVoltageValue', models.FloatField()),
                ('batteryVoltageValue', models.FloatField()),
                ('batteryCurrentValue', models.FloatField()),
                ('batteryTemperatureValue', models.FloatField()),
                ('batteryTimeLeftValue', models.FloatField()),
                ('batteryRemainingCapacityValue', models.FloatField()),
                ('batteryUsedCapacityValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TodayPOPMSA006ExternalInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deviceCode', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('mainVoltage', models.FloatField()),
                ('rectifierCurrent', models.FloatField()),
                ('loadCurrentValue', models.FloatField()),
                ('loadVoltageValue', models.FloatField()),
                ('batteryVoltageValue', models.FloatField()),
                ('batteryCurrentValue', models.FloatField()),
                ('batteryTemperatureValue', models.FloatField()),
                ('batteryTimeLeftValue', models.FloatField()),
                ('batteryRemainingCapacityValue', models.FloatField()),
                ('batteryUsedCapacityValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='HourlyTemporaryPOPMSA006ExternalInfo',
        ),
    ]
