# Generated by Django 4.1 on 2024-09-25 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0007_remove_last30dayspopmsa006_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 540599, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 539943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 537712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temporarypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 538439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 541272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todaypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 48, 45, 539108, tzinfo=datetime.timezone.utc)),
        ),
    ]
