# Generated by Django 4.1 on 2024-09-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0008_alter_last30dayspopmsa006externalinfo_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 241984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 241282, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 239058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temporarypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 239769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 242696, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todaypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 55, 35, 240487, tzinfo=datetime.timezone.utc)),
        ),
    ]
