# Generated by Django 4.1 on 2024-09-25 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0009_alter_last30dayspopmsa006externalinfo_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 434239, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 433421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 430692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temporarypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 431542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 435017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todaypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 58, 55, 432334, tzinfo=datetime.timezone.utc)),
        ),
    ]
