# Generated by Django 4.1 on 2024-09-25 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0012_alter_last30dayspopmsa006externalinfo_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30dayspopmsa006',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 750917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last30dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 757467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 749687, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 756686, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='popmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 754418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temporarypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 755210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 752161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 758194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todaypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 15, 39, 755978, tzinfo=datetime.timezone.utc)),
        ),
    ]
