# Generated by Django 4.1 on 2024-09-26 06:19

from django.db import migrations, models
import pops.POPMSA006_mongo_models
import pops.temporary_popmsa006_models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0013_alter_last30dayspopmsa006_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30dayspopmsa006',
            name='created_time',
            field=models.DateTimeField(default=pops.POPMSA006_mongo_models.default_time),
        ),
        migrations.AlterField(
            model_name='last30dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006',
            name='created_time',
            field=models.DateTimeField(default=pops.POPMSA006_mongo_models.default_time),
        ),
        migrations.AlterField(
            model_name='last7dayspopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
        migrations.AlterField(
            model_name='popmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
        migrations.AlterField(
            model_name='temporarypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006',
            name='created_time',
            field=models.DateTimeField(default=pops.POPMSA006_mongo_models.default_time),
        ),
        migrations.AlterField(
            model_name='thisyearpopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
        migrations.AlterField(
            model_name='todaypopmsa006externalinfo',
            name='created_time',
            field=models.DateTimeField(default=pops.temporary_popmsa006_models.default_time),
        ),
    ]
